name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install the required packages
      run: |
        sudo apt-get update 
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-pictures texlive-science 
        sudo apt-get clean
    - name: Build the Thesis
      run: make
    - uses: actions/upload-artifact@master
      with:
        name: Compiled Thesis
        path: ./thesis.pdf
